version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # host:container (Nginx sirve en 80)
    depends_on:
      - backend
    networks:
      - appnet

  db:
    image: postgres:15
    container_name: app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - appnet

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/appdb
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
